language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ccorreag/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ccorreag/react-test npm test -- --coverage

after_success:
    - docker build -t ccorreag/multi-client ./client
    - docker build -t ccorreag/multi-server ./server
    - docker build -t ccorreag/multi-worker ./worker
    - docker build -t ccorreag/multi-nginx ./nginx
    # Log in to the docker CLI
    - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    # take those images images and push them to docker hub
    - docker push ccorreag/multi-client
    - docker push ccorreag/multi-server
    - docker push ccorreag/multi-worker
    - docker push ccorreag/multi-nginx
