version: '3.1'
services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres_password
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on: 
            - api
            - client
    api:
        depends_on: 
            - postgres
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            

